# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cddfba89849c27e852b61b3cc9c9fbbb7eefdf3d028ff7127af4d53859352d932fe843afbc90f071d7c339b4e1665ad6168d7f675efca3b58440451554754c0e

test:
  secret_key_base: 9607a93d01d44edf6499ce30c76e8bf4058b5a6d387546262347e5a5bf5a978e6740d08b4b04a84d38a2ff5e9d7340afa15f3e6c8f614d35514e04880fed15c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
